service: f3-scheduler

configValidationMode: error

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  environment:
    PAX_TABLE: f3-scheduler-pax
    REGIONS_TABLE: f3-scheduler-regions
    AOS_TABLE: f3-scheduler-aos
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:PutItem
            - dynamodb:GetItem
          Resource: "arn:aws:dynamodb:*:*:table/${self:provider.environment.AOS_TABLE}"
        - Effect: "Allow"
          Action:
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:PutItem
            - dynamodb:GetItem
          Resource: "arn:aws:dynamodb:*:*:table/${self:provider.environment.PAX_TABLE}"
        - Effect: "Allow"
          Action:
            - dynamodb:Scan
            - dynamodb:UpdateItem
            - dynamodb:PutItem
            - dynamodb:GetItem
          Resource: "arn:aws:dynamodb:*:*:table/${self:provider.environment.REGIONS_TABLE}"


functions:
  updateAo:
    handler: backend/update_ao.handler
    events:
      - http:
          path: aos
          method: post
          cors: true
  listAos:
    handler: backend/get_ao.getAll
    events:
      - http:
          path: aos
          method: get
          cors: true
  getAoDetails:
    handler: backend/get_ao.getById
    events:
      - http:
          path: aos/{id}
          method: get
          cors: true
  updatePax:
    handler: backend/update_pax.handler
    events:
      - http:
          path: pax
          method: post
          cors: true
  listPax:
    handler: backend/get_pax.getAll
    events:
      - http:
          path: pax
          method: get
          cors: true
  getPaxDetails:
    handler: backend/get_pax.getById
    events:
      - http:
          path: pax/{id}
          method: get
          cors: true
  updateRegion:
    handler: backend/update_region.handler
    events:
      - http:
          path: regions
          method: post
          cors: true
  listRegions:
    handler: backend/get_region.getAll
    events:
      - http:
          path: regions
          method: get
          cors: true
  getRegionDetails:
    handler: backend/get_region.getById
    events:
      - http:
          path: regions/{id}
          method: get
          cors: true

resources:
  Resources:
    aosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.AOS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    paxTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PAX_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    regionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.REGIONS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
